import { useMemo, useState } from 'react';
import { Activity, Eye, Image as ImageIcon, LoaderCircle, ScanFace, Upload } from 'lucide-react';

type AnalyzeResponse = {
  status: string;
  detected_face: boolean;
  predicted_name: string | null;
  similarity: number;
  confidence: number;
  fps: number;
  input_image_base64: string;
  reconstructed_image_base64: string;
  original_image_base64?: string;
};

const API_BASE_URL = `http://${window.location.hostname}:8001`;

function toDataUrl(base64: string | undefined) {
  return base64 ? `data:image/png;base64,${base64}` : null;
}

function metricLabel(value: number | null | undefined, digits = 2) {
  if (value === null || value === undefined || Number.isNaN(value)) {
    return '--';
  }
  return value.toFixed(digits);
}

export default function App() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [localPreview, setLocalPreview] = useState<string | null>(null);
  const [result, setResult] = useState<AnalyzeResponse | null>(null);
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const imageCards = useMemo(
    () => [
      {
        title: 'Original Face',
        subtitle: result?.original_image_base64
          ? 'Reference image from the identity predicted by the recognition model'
          : 'Available when the recognition model finds a matching gallery identity',
        image: toDataUrl(result?.original_image_base64),
      },
      {
        title: 'Occluded Input',
        subtitle: 'The uploaded masked or partially occluded face',
        image: localPreview,
      },
      {
        title: 'Reconstructed Face',
        subtitle: 'Generated by the reconstruction model',
        image: toDataUrl(result?.reconstructed_image_base64),
      },
    ],
    [localPreview, result],
  );

  async function handleUpload(file: File) {
    setSelectedFile(file);
    setLocalPreview(URL.createObjectURL(file));
    setError(null);
    setProcessing(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append('file', file);

      const response = await fetch(`${API_BASE_URL}/analyze`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        throw new Error(`Backend returned ${response.status}`);
      }

      const payload = (await response.json()) as AnalyzeResponse;
      setResult(payload);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to analyze the uploaded image.');
    } finally {
      setProcessing(false);
    }
  }

  return (
    <div className="app-shell">
      <div className="hero-grid">
        <section className="hero-copy">
          <p className="eyebrow">Hybrid OFR Viewer</p>
          <h1>Compare original, occluded, and reconstructed faces in one place.</h1>
          <p className="lead">
            Upload an image from your occluded dataset and the site will call the local backend, reconstruct the face,
            predict the person name, and show the original LFW reference image for the predicted identity.
          </p>

          <div className="metric-strip">
            <div className="metric-card">
              <span className="metric-label">Detected Face</span>
              <span className="metric-value">{result ? (result.detected_face ? 'Yes' : 'No') : '--'}</span>
            </div>
            <div className="metric-card">
              <span className="metric-label">Predicted Name</span>
              <span className="metric-value metric-name">{result?.predicted_name ?? '--'}</span>
            </div>
            <div className="metric-card">
              <span className="metric-label">Confidence</span>
              <span className="metric-value">{metricLabel(result?.confidence, 4)}</span>
            </div>
            <div className="metric-card">
              <span className="metric-label">Speed</span>
              <span className="metric-value">{result ? `${metricLabel(result.fps)} FPS` : '--'}</span>
            </div>
          </div>
        </section>

        <section className="panel upload-panel">
          <div className="panel-header">
            <div>
              <p className="eyebrow">Input</p>
              <h2>Analyze an occluded face</h2>
            </div>
            <Activity className={`panel-icon ${processing ? 'is-spinning' : ''}`} />
          </div>

          <label className="upload-dropzone">
            <input
              type="file"
              accept="image/*"
              onChange={(event) => {
                const file = event.target.files?.[0];
                if (file) {
                  void handleUpload(file);
                }
              }}
            />
            <Upload size={24} />
            <div>
              <p>{selectedFile ? selectedFile.name : 'Choose an occluded image'}</p>
              <span>Best for files from `processed_lfw_partial`, `processed_lfw`, or `processed_lfw_heavy`.</span>
            </div>
          </label>

          <div className="status-box">
            {processing ? (
              <>
                <LoaderCircle size={18} className="is-spinning" />
                <span>Running reconstruction and identity analysis against the local backend.</span>
              </>
            ) : error ? (
              <span className="error-text">{error}</span>
            ) : (
              <span>Backend endpoint: `{API_BASE_URL}/analyze`</span>
            )}
          </div>

          <div className="score-grid">
            <div className="score-box">
              <ScanFace size={18} />
              <div>
                <span className="score-label">Similarity</span>
                <strong>{metricLabel(result?.similarity, 4)}</strong>
              </div>
            </div>
            <div className="score-box">
              <Eye size={18} />
              <div>
                <span className="score-label">Preview Ready</span>
                <strong>{result?.reconstructed_image_base64 ? 'Yes' : 'No'}</strong>
              </div>
            </div>
          </div>
        </section>
      </div>

      <section className="panel gallery-panel">
        <div className="panel-header">
          <div>
            <p className="eyebrow">Viewer</p>
            <h2>Side-by-side image comparison</h2>
          </div>
          <ImageIcon className="panel-icon" />
        </div>

        <div className="image-grid">
          {imageCards.map((card) => (
            <article key={card.title} className="image-card">
              <div className="image-card-copy">
                <h3>{card.title}</h3>
                <p>{card.subtitle}</p>
              </div>
              <div className="image-frame">
                {card.image ? (
                  <img src={card.image} alt={card.title} />
                ) : (
                  <div className="image-placeholder">
                    <ImageIcon size={28} />
                    <span>No image loaded yet</span>
                  </div>
                )}
              </div>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}
